# Site
repository: Trisha11r/Trisha11r.github.io
favicon: images/favicon.ico
   
#     <div class = "change_head_color" style = "background-color:#115088;">
# Personal info
name: Trisha Kanji
title: SUNY Stony Brook CS Grad Student
email: trisha.kanji@stonybrook.edu
website: https://trisha11r.github.io
resume: https://trisha11r.github.io/KanjiTrisha2020.pdf

# Social links

github_username:  Trisha11r
# dribbble_username:
facebook_username: trisha.kanji
# flickr_username:
# instagram_username: treeeshaah
linkedin_username: trisha-kanji
twitter_username: KanjiTrisha
# pinterest_username:
youtube_username: channel/UCa0-ECew513rrDNKm2mjfow/videos?view_as=subscriber
# googleplus_username:
#     </div>

# About Section
# about_title: About Me
about_profile_image: images/jg.jpg
about_content: |
  Hi, I am a Computer Science Graduate Student doing my Masters from the State University of New York at Stony Brook.
  I code mainly in, <b>python</b> and <b>java</b>. I seek to contribute towards real-world problem solving and  delve deeper into the nuances of Software and Intelligent Systems. My interests lie in the domains of <b>machine learning, data analysis and visualization</b>. The things that I currently have the most experience working with are:
  <b>D3.js</b>,
  <b>HTML/CSS/Javascript</b>,
  <b>Numpy/Scipy</b>,
  <b>Pandas</b>,
  <b>Sklearn</b>,
  <b>Seaborn</b>,
  <b>Tensorflow</b>,
  <b>Jupyter</b>,
  <b>Google Colab</b>,
  <b>SQL(MySQL, DB2, Oracle)</b>.
  
  
  <h3>Skills</h3>
  
  <style>
    .skills{
      list-style: none;
      padding: 0;
      width: 100%;
      color: #black;
    }
    .skills li{
      margin: 20px 0;
    }
    .bar{
      background: #ccffff;
      display: block;
      height: 10px;
      border: 1px solid rgba(0,0,0,0.3);
      border-radius: 3px;
      overflow: hidden;
      box-shadow: 0 0 10px #4246a9;
    }
    .bar span{
      height: 10px;
      float: left;
      background: #009999;
    }
    
    .java{
      width: 80%;
      animation: java 2s;
    }
    .python{
      width: 90%;
      animation: python 2s;
    }
    .javascript{
      width: 70%;
      animation: javascript 2s;
      }
    .plsql{
      width: 70%;
      animation: javascript 2s;
      }
    .htmlcss{
      width: 70%;
      animation: javascript 2s;
      }
    .cplus{
      width: 50%;
      animation: cplus 2s;
    }
    .xquery{
      width: 50%;
      animation: cplus 2s;
      }
    .c{
      width: 40%;
      animation: c 2s;
    }
    
    @keyframes java{
      0%{
        width: 0%;
      }
      100%{
        width: 80%;
      }
    }
    @keyframes python{
      0%{
        width: 0%;
      }
      100%{
        width: 90%;
      }
    }
    @keyframes javascript{
      0%{
        width: 0%;
      }
      100%{
        width: 70%;
      }
    }
    @keyframes cplus{
      0%{
        width: 0%;
      }
      100%{
        width: 50%;
      }
    }
    @keyframes c{
      0%{
        width: 0%;
      }
      100%{
        width: 40%;
      }
    }
    /* Create two equal columns that floats next to each other */
    .column {
      float: left;
      width: 50%;
      padding: 10px;
      height: 300px; /* Should be removed. Only for demonstration */
    }
    /* Clear floats after the columns */
    .skills:after {
      content: "";
      display: table;
      clear: both;
    }
    /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
    @media screen and (max-width: 600px) {
      .column {
        width: 100%;
      }
    </style>
  
  <div class="skills">
    <div class="column">
      <li>
        <p>Python</p><span class="bar"><span class="python"></span></span>
      </li>
      <li>
        <p>JavaScript/D3.js</p><span class="bar"><span class="javascript"></span></span>
      </li>
      <li>
        <p>PL/SQL</p><span class="bar"><span class="plsql"></span></span>
      </li>
      <li>
        <p>C++</p><span class="bar"><span class="cplus"></span></span>
      </li>
      
    </div>
    <div class="column">
      <li>
        <p>Java</p><span class="bar"><span class="java"></span></span>
      </li>
      <li>
        <p>HTML/CSS/Bootstrap</p><span class="bar"><span class="htmlcss"></span></span>
      </li>
      <li>
        <p>XQuery/XPath</p><span class="bar"><span class="xquery"></span></span>
      </li>
      <li>
        <p>C</p><span class="bar"><span class="c"></span></span>
      </li>
    </div>
  </div>

# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
more_title: Interests and Accomplishments
more_content: |
      My other interests include Music and Robotics. 
      In whatever little spare time I get, I try to engage myself in good music. I am a trained vocalist in <b>Indian Classical Music</b> (Hindustani) and have completed my <b>Vid (6 year Diploma Course) with Distinction in Music(Vocals)</b>, from the esteemed institution, <b>Indira Kala Sangeet Vishwavidyalaya (I.K.S.V.Khairagarh)</b>.
      The quintessential role that the domains of computer vision and robotics play in value addition towards life enthralls me. During my time at IIEST, Shibpur, I served as the <b>Computer Vision Sub-Head</b> (2015-16) of <b>Robodarshan</b>, the institute's robotics society. I also secued <b>1st</b> position in a <b>vision guided autonomous robotics</b> event based on character recognition using image processing and equation optimization at the annual tech- fest of IIT,Kharagpur (S.H.E.L.D.O.N. Kshitij 2016).
      
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
