# Site
repository: Trisha11r/Trisha11r.github.io

favicon: images/favicon.ico

# Personal info
name: Trisha Kanji
title: SUNY Stony Brook Graduate Student
email: trisha.kanji@stonybrook.edu
website: https://trisha11r.github.io

# Social links
# twitter_username: shanuj
github_username:  Trisha11r
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: shanuj9708
linkedin_username: trisha-kanji
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/jg.jpg
about_content: |
  Hi, my name is Trisha Kanji, I'm a Computer Science Graduate Student doing my Master's Program from the State University of New York at Stony Brook.
  I am currently working for the Royal Bank of Scotland as a frontend software engineer on a comercial banking platform.

  I enjoy making clean and interactive UI that is quick and easy to use whilst also giving users an enjoyable experience.
  I have worked with a range of different languages and frameworks and I am always looking for opportunities to work
  with something new. The things that I currently have the most experience working with are:
  <mark>ES6 Javascript</mark>,
  <mark>React &amp; Redux</mark>,
  <mark>Java</mark>,
  <mark>PHP</mark>,
  <mark>MySQL</mark>,
  <mark>Symfony</mark>,
  <mark>Android</mark>,
  <mark>SASS</mark>,
  <mark>git</mark> and
  <mark>AWS</mark> services.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Interests and Accomplishments
more_content: |
 Indira Kala Sangeet Vishwavidyalaya “IKSV” : Completed Vid(6 year Diploma Course) with Distinction in Music(Vocals), 
 in the field of Indian Classical Music (Hindustani).
  

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
