# Site
repository: Trisha11r/Trisha11r.github.io

favicon: images/favicon.ico

# Personal info
name: Trisha Kanji
title: SUNY Stony Brook CS Grad Student
email: trisha.kanji@stonybrook.edu
website: https://trisha11r.github.io

# Social links
# twitter_username: shanuj
github_username:  Trisha11r
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: shanuj9708
linkedin_username: trisha-kanji
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/jg.jpg
about_content: |
  Hi, I am a Computer Science Graduate Student doing my Masters from the State University of New York at Stony Brook.
  I code mainly in, <mark>python</mark> and <mark>java</mark>. I seek to contribute towards real-world problem solving and  delve deeper into the nuances of Software and Intelligent Systems. My interests lie in the domains of machine learning, data analysis and visualization. The things that I currently have the most experience working with are:
  <mark>D3.js</mark>,
  <mark>HTML/CSS/Javascript</mark>,
  <mark>Numpy/Scipy</mark>,
  <mark>Pandas</mark>,
  <mark>Sklearn</mark>,
  <mark>Seaborn</mark>,
  <mark>Tenserflow</mark>,
  <mark>Jupyter</mark>,
  <mark>Google Colab</mark>,
  <mark>SQL(MySQL, DB2, Oracle)</mark>.

# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
more_title: Interests and Accomplishments
more_content: |
 Indira Kala Sangeet Vishwavidyalaya “IKSV” : Completed Vid(6 year Diploma Course) with Distinction in Music(Vocals), 
 in the field of Indian Classical Music (Hindustani).
  

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
